[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
    [headers.values]
      cache-control = "public, max-age=31536000, immutable"
      Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-XSS-Protection = "1; mode=block"
      Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; worker-src 'self'; frame-ancestors 'none';"

[[headers]]
  for = "/index.html"
    [headers.values]
      cache-control = "no-cache"


[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/js-yaml.min.js"
  to = "/js-yaml.min.js"
  status = 200

[[redirects]]
  from = "/xmllint.js"
  to = "/xmllint.js"
  status = 200

[[redirects]]
  from = "/sidebar.js"
  to = "/sidebar.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
